import type { Config } from 'tailwindcss'

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#370e00",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffdbce",
        "surface-bright": "#f7f9fb",
        "primary-fixed-dim": "#bec6e0",
        "secondary-fixed": "#d5e3fc",
        "outline": "#76777d",
        "outline-variant": "#c6c6cd",
        "surface-variant": "#e0e3e5",
        "on-tertiary-fixed-variant": "#7f2b00",
        "error": "#ba1a1a",
        "secondary": "#515f74",
        "inverse-on-surface": "#eff1f3",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eceef0",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#131b2e",
        "secondary-fixed-dim": "#b9c7df",
        "on-primary-container": "#7c839b",
        "inverse-surface": "#2d3133",
        "inverse-primary": "#bec6e0",
        "surface-dim": "#d8dadc",
        "surface-container-low": "#f2f4f6",
        "secondary-container": "#d5e3fc",
        "background": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "on-secondary-fixed-variant": "#3a485b",
        "on-surface": "#191c1e",
        "error-container": "#ffdad6",
        "text-main": "#161616",
        "surface-tint": "#565e74",
        "primary-fixed": "#dae2fd",
        "tertiary-fixed-dim": "#ffb599",
        "tertiary": "#000000",
        "surface": "#f7f9fb",
        "border-subtle": "#E2E8F0",
        "on-surface-variant": "#45464d",
        "on-secondary-fixed": "#0d1c2e",
        "surface-container-highest": "#e0e3e5",
        "surface-dark": "#1E293B",
        "safety-orange-muted": "#FB923C",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#370e00",
        "on-primary-fixed-variant": "#3f465c",
        "on-background": "#191c1e",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#e45405",
        "primary": "#000000",
        "on-tertiary": "#ffffff",
        "primary-container": "#131b2e",
        "on-secondary-container": "#57657a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-sm": "0.5rem",
        "container-max": "1280px",
        "stack-md": "1.5rem",
        "margin-mobile": "1rem",
        "gutter": "1.5rem",
        "margin-desktop": "2.5rem",
        "stack-lg": "3rem"
      },
      fontFamily: {
        "headline-lg-mobile": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "display": ["Hanken Grotesk"],
        "button": ["Inter"],
        "body-lg": ["Hanken Grotesk"],
        "label-caps": ["Inter"],
        "headline-md": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "display": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "button": ["16px", {"lineHeight": "20px", "fontWeight": "600"}],
        "body-lg": ["20px", {"lineHeight": "30px", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
} satisfies Config
